import os
import re
import yaml
from pathlib import Path
from collections import Counter

CONTENT_DIR = Path("/Users/apple/aiagentautomation/src/content/agents")

def parse_frontmatter(content):
    match = re.search(r'^---\s+(.*?)\s+---', content, re.DOTALL)
    if not match:
        return None
    try:
        return yaml.safe_load(match.group(1))
    except:
        return None

def debug_app():
    print("--- Debugging App Data ---")
    
    agents = []
    categories = set()
    
    for f in CONTENT_DIR.glob("*.md"):
        data = parse_frontmatter(f.read_text())
        if not data:
            print(f"Invalid frontmatter: {f.name}")
            continue
            
        slug = f.stem
        cat = data.get('category', 'Uncategorized')
        
        # Check for messy categories
        if '[' in cat or '(' in cat:
             print(f"[WARN] Agent '{slug}' has content in category: '{cat}'")
             
        categories.add(cat)
        agents.append({'slug': slug, 'category': cat})
        
    print(f"\nTotal Agents: {len(agents)}")
    print(f"Total Unique Categories: {len(categories)}")
    
    print("\n--- Category Link Simulation ---")
    # Simulate CategoryFilter.astro logic: name.toLowerCase().replace(/\s+/g, '-')
    seen_slugs = {}
    for cat in sorted(categories):
        slug = cat.lower().replace(' ', '-') # Python's replace is exact, JS replace(/\s+/g) handles multiple spaces
        slug = re.sub(r'\s+', '-', cat.lower())
        
        print(f"'{cat}' -> '/categories/{slug}/'")
        
        if slug in seen_slugs:
            print(f"  [CONFLICT] Slug '{slug}' already generated by '{seen_slugs[slug]}'")
        seen_slugs[slug] = cat

    # Check for layout/page existence (simulated)
    # We know src/pages/categories/[slug].astro is missing, confirming the 404s.

if __name__ == "__main__":
    debug_app()
